//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Essential {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Essential.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string ActivityScope_Start {
            get {
                return ResourceManager.GetString("ActivityScope_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string ActivityScope_Stop {
            get {
                return ResourceManager.GetString("ActivityScope_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string ActivityScope_Transfer {
            get {
                return ResourceManager.GetString("ActivityScope_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console color specified is invalid..
        /// </summary>
        internal static string InvalidConsoleColor {
            get {
                return ResourceManager.GetString("InvalidConsoleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhausted possible logfile names..
        /// </summary>
        internal static string RollingTextWriter_ExhaustedLogfileNames {
            get {
                return ResourceManager.GetString("RollingTextWriter_ExhaustedLogfileNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument name used..
        /// </summary>
        internal static string StringTemplate_ArgumentNotFound {
            get {
                return ResourceManager.GetString("StringTemplate_ArgumentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string was not a correct template..
        /// </summary>
        internal static string StringTemplate_InvalidString {
            get {
                return ResourceManager.GetString("StringTemplate_InvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, relatedActivityId={1}.
        /// </summary>
        internal static string TraceListenerBase_TraceMessageFormat {
            get {
                return ResourceManager.GetString("TraceListenerBase_TraceMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: {0}.
        /// </summary>
        internal static string TraceLog_AppendedExceptionFormat {
            get {
                return ResourceManager.GetString("TraceLog_AppendedExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        internal static string TraceLog_ExceptionFormatSeparator {
            get {
                return ResourceManager.GetString("TraceLog_ExceptionFormatSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type argument TEventId is not an enum or int: {0}.
        /// </summary>
        internal static string TraceLog_InvalidTEventId {
            get {
                return ResourceManager.GetString("TraceLog_InvalidTEventId", resourceCulture);
            }
        }
    }
}
